# Generated by Django 4.1.6 on 2023-02-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="delivery_instructions",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Delivery Instructions"
            ),
        ),
    ]
