version: '3'

services:
  db:
    container_name: ecommerce_postgres_db
    image: 'postgres:latest'
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .postgres_env
    ports:
      - 5432:5432
    