version: "3.1"

services:
  db:
    container_name: ecommerce_postgres_db
    image: "postgres:15.1"
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .postgres_env
    ports:
      - 5432:5432
